# NB: this is only used for local development
# see Dockerfile for deployed version

# To col=mpletely reset the database add the following in front of the command
# venv/bin/python manage.py reset_db --noinput

db:
  build: docker/postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
django:
  build: .
  ports:
    - "8000:8000"
  links:
    - db
  environment:
    ENV: local
    DEBUG: "True"
    DJANGO_SECRET_KEY: BIG_SECRET
    DJANGO_SETTINGS_MODULE: dashboard.settings.base
    DB_NAME: dashboard
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    DB_HOST: db
    DB_PORT: 5432
